export enum routerPaths {
  ButtonHover = '/',
  CardRotate = '/card-rotate',
  BeveledCorners = '/beveled-corners',
  CreativeButtonHover = '/creative-button-hover',
  NeonButton = '/neon-button',
  ErrorPage = '*',
  ResponsiveMenu = 'responsive-menu',
  AnimatedIndicator = '/animated-indicator',
  ThreeDRotate = '/three-d-rotate',
  AnimatedTextLoading = '/animated-text-loading',
  AnimButtonWithGradient = '/anim-button-with-gradient',
  CircleProgressBar = 'circle-progress-bar',
  DropsElements = 'drops-elements',
}
